config: /Users/alicec03/Desktop/Summer_Research/Photo-z-Stress-Test/Photo-z-Stress-Test/GPz/BOSS/BOSS_TrainZ_config.yml
inputs:
  model: /Users/alicec03/Desktop/Summer_Research/Photo-z-Stress-Test/Photo-z-Stress-Test/data/5e5_trained_flow.pkl
log_dir: .
modules: rail
output_dir: .
resume: false
site:
  dry_run: false
  max_threads: 2
  name: local
  python_paths: []
stages:
- classname: FlowCreator
  module_name: rail.creation.engines.flowEngine
  name: spec_train_set
  nprocess: 1
- classname: FlowCreator
  module_name: rail.creation.engines.flowEngine
  name: test_set
  nprocess: 1
- classname: LSSTErrorModel
  module_name: rail.creation.degradation.lsst_error_model
  name: lsst_error
  nprocess: 1
- classname: TrainZInformer
  module_name: rail.estimation.algos.train_z
  name: inform_TrainZ
  nprocess: 1
- classname: TrainZEstimator
  module_name: rail.estimation.algos.train_z
  name: estimate_TrainZ
  nprocess: 1
- classname: specselection_boss
  module_name: rail.creation.degradation.spectroscopic_selections
  name: specselection_boss
  nprocess: 1
- classname: LSSTErrorModel
  module_name: rail.creation.degradation.lsst_error_model
  name: lsst_error_0
  nprocess: 1
