col_remapper:
  aliases:
    input: output_lsst_error_model_deg
    output: output_col_remapper
  chunk_size: 100000
  columns:
    mag_g_lsst_err: mag_err_g_lsst
    mag_i_lsst_err: mag_err_i_lsst
    mag_r_lsst_err: mag_err_r_lsst
    mag_u_lsst_err: mag_err_u_lsst
    mag_y_lsst_err: mag_err_y_lsst
    mag_z_lsst_err: mag_err_z_lsst
  config: null
  inplace: false
  input: None
  name: col_remapper
  output_mode: default
flow_creator_test:
  aliases:
    model: model_flow_modeler
    output: output_flow_creator_test
  config: null
  model: /Users/alicec03/Desktop/Summer Research /Photo-z-Stress-Test/Photo-z-Stress-Test/data/trained_flow.pkl
  n_samples: 100000
  name: flow_creator_test
  output_mode: default
  seed: 472
flow_creator_train:
  aliases:
    model: model_flow_modeler
    output: output_flow_creator_train
  config: null
  model: /Users/alicec03/Desktop/Summer_Research/Photo-z-Stress-Test/Photo-z-Stress-Test/data/trained_flow.pkl
  n_samples: 10000
  name: flow_creator_train
  output_mode: default
  seed: 1235
flow_modeler:
  aliases:
    model: model_flow_modeler
  calc_colors:
    ref_column_name: mag_i_lsst
  config: null
  input: /Users/alicec03/Desktop/Summer_Research/Photo-z-Stress-Test/Photo-z-Stress-Test/data/base_catalog.pq
  model: /Users/alicec03/Desktop/Summer_Research/Photo-z-Stress-Test/Photo-z-Stress-Test/data/trained_flow.pkl
  name: flow_modeler
  num_training_epochs: 30
  output_mode: default
  phot_cols:
    mag_g_lsst:
    - 16
    - 32
    mag_i_lsst:
    - 15
    - 30
    mag_r_lsst:
    - 15
    - 30
    mag_u_lsst:
    - 17
    - 35
    mag_y_lsst:
    - 14
    - 28
    mag_z_lsst:
    - 14
    - 29
  phys_cols:
    redshift:
    - 0
    - 3
  seed: 0
  spline_knots: 16
inform_FZBoost:
  aliases:
    input: output_inv_redshift_deg
    model: model_inform_FZBoost
  bands: &id001
  - mag_u_lsst
  - mag_g_lsst
  - mag_r_lsst
  - mag_i_lsst
  - mag_z_lsst
  - mag_y_lsst
  basis_system: cosine
  bumpmax: 0.35
  bumpmin: 0.02
  config: null
  err_bands: &id002
  - mag_err_u_lsst
  - mag_err_g_lsst
  - mag_err_r_lsst
  - mag_err_i_lsst
  - mag_err_z_lsst
  - mag_err_y_lsst
  hdf5_groupname: ''
  input: None
  mag_limits: &id003
    mag_g_lsst: 29.04
    mag_i_lsst: 28.62
    mag_r_lsst: 29.06
    mag_u_lsst: 27.79
    mag_y_lsst: 27.05
    mag_z_lsst: 27.98
  max_basis: 35
  model: fzboost.pkl
  name: inform_FZBoost
  nbump: 20
  nondetect_val: 99.0
  nsharp: 15
  nzbins: 301
  output_mode: default
  redshift_col: redshift
  ref_band: mag_i_lsst
  regression_params:
    learning_rate: 0.3
    max_depth: 8
    objective: reg:squarederror
    silent: 1
  save_train: true
  seed: 1138
  sharpmax: 2.1
  sharpmin: 0.7
  trainfrac: 0.75
  zmax: 3.0
  zmin: 0.0
inv_redshift_deg:
  aliases:
    input: output_flow_creator_train
    output: output_inv_redshift_deg
  config: null
  input: None
  name: inv_redshift_deg
  output_mode: default
  pivot_redshift: 1.0
  seed: 12345
lsst_error_model_deg:
  A_max: 2.0
  A_min: 0.7
  Cm:
    g: 24.42
    i: 24.32
    r: 24.44
    u: 23.09
    y: 23.73
    z: 24.16
  airmass: 1.2
  aliases:
    input: output_flow_creator_test
    output: output_lsst_error_model_deg
  bandNames:
    g: mag_g_lsst
    i: mag_i_lsst
    r: mag_r_lsst
    u: mag_u_lsst
    y: mag_y_lsst
    z: mag_z_lsst
  config: null
  errorType: point
  extendedSource: 0.0
  gamma:
    g: 0.039
    i: 0.039
    r: 0.039
    u: 0.038
    y: 0.039
    z: 0.039
  highSNR: false
  input: None
  km:
    g: 0.213
    i: 0.096
    r: 0.126
    u: 0.491
    y: 0.17
    z: 0.069
  m5: {}
  magLim: 30.0
  msky:
    g: 22.26
    i: 20.48
    r: 21.2
    u: 22.99
    y: 18.61
    z: 19.6
  nVisYr:
    g: 8.0
    i: 18.4
    r: 18.4
    u: 5.6
    y: 16.0
    z: 16.0
  nYrObs: 10.0
  name: lsst_error_model_deg
  ndFlag: .nan
  output_mode: default
  seed: 66
  sigmaSys: 0.005
  theta:
    g: 0.77
    i: 0.71
    r: 0.73
    u: 0.81
    y: 0.68
    z: 0.69
  tvis: 30.0
table_conv:
  aliases:
    input: output_col_remapper
    output: output_table_conv
  config: null
  input: None
  name: table_conv
  output_format: numpyDict
  output_mode: default
test_FZBoost:
  aliases:
    input: output_lsst_error_model_deg
    model: model_inform_FZBoost
    output: output_test_FZBoost
  bands: *id001
  chunk_size: 10000
  config: null
  err_bands: *id002
  hdf5_groupname: ''
  input: None
  mag_limits: *id003
  model: fzboost.pkl
  name: test_FZBoost
  nondetect_val: .nan
  nzbins: 301
  output_mode: default
  qp_representation: interp
  ref_band: mag_i_lsst
