col_remapper_1:
  aliases:
    input: output_quantity_cut_1
    output: output_col_remapper_1
  chunk_size: 100000
  columns: &id001
    mag_g_lsst_err: mag_err_g_lsst
    mag_i_lsst_err: mag_err_i_lsst
    mag_r_lsst_err: mag_err_r_lsst
    mag_u_lsst_err: mag_err_u_lsst
    mag_y_lsst_err: mag_err_y_lsst
    mag_z_lsst_err: mag_err_z_lsst
  config: null
  inplace: false
  input: None
  name: col_remapper_1
  output_mode: default
col_remapper_2:
  aliases:
    input: output_quantity_cut_2
    output: output_col_remapper_2
  chunk_size: 100000
  columns: *id001
  config: null
  inplace: false
  input: None
  name: col_remapper_2
  output_mode: default
estimate_CMNN:
  aliases:
    input: output_col_remapper_2
    model: model_inform_CMNN
    output: output_estimate_CMNN
  bad_redshift_err: 10.0
  bad_redshift_val: 99.0
  bands: &id002
  - mag_u_lsst
  - mag_g_lsst
  - mag_r_lsst
  - mag_i_lsst
  - mag_z_lsst
  - mag_y_lsst
  calculated_point_estimates: []
  chunk_size: 10000
  config: null
  err_bands: &id003
  - mag_err_u_lsst
  - mag_err_g_lsst
  - mag_err_r_lsst
  - mag_err_i_lsst
  - mag_err_z_lsst
  - mag_err_y_lsst
  hdf5_groupname: ''
  input: None
  mag_limits: &id004
    mag_g_lsst: 29.04
    mag_i_lsst: 28.62
    mag_r_lsst: 29.06
    mag_u_lsst: 27.79
    mag_y_lsst: 27.05
    mag_z_lsst: 27.98
  min_dist: 0.0001
  min_n: 25
  min_thresh: 0.0001
  model: invz=0.6_cmnn.pkl
  name: estimate_CMNN
  nondetect_val: 99.0
  nzbins: 301
  output_mode: default
  ppf_value: 0.68
  redshift_col: redshift
  seed: 66
  selection_mode: 1
  zmax: 3.0
  zmin: 0.0
inform_CMNN:
  aliases:
    input: output_col_remapper_1
    model: model_inform_CMNN
  bands: *id002
  config: null
  err_bands: *id003
  hdf5_groupname: ''
  input: None
  mag_limits: *id004
  model: invz=0.6_cmnn.pkl
  name: inform_CMNN
  nondetect_replace: false
  nondetect_val: 99.0
  output_mode: default
  redshift_col: redshift
  save_train: true
inv_redshift:
  aliases:
    input: output_invz_train_set
    output: output_inv_redshift
  config: null
  input: None
  name: inv_redshift
  output_mode: default
  pivot_redshift: 0.6
  seed: 12345
invz_train_set:
  aliases:
    output: output_invz_train_set
  config: null
  model: /Users/alicec03/Desktop/Summer_Research/Photo-z-Stress-Test/Photo-z-Stress-Test/data/1e6_trained_flow.pkl
  n_samples: 100000
  name: invz_train_set
  output_mode: default
  seed: 17
lsst_error:
  Cm: &id005
    g: 24.42
    i: 24.32
    r: 24.44
    u: 23.09
    y: 23.73
    z: 24.16
  aMax: 2.0
  aMin: 0.7
  absFlux: false
  airmass: 1.2
  aliases:
    input: output_test_set
    output: output_lsst_error
  config: null
  decorrelate: true
  errLoc: after
  extendedType: point
  gamma: &id006
    g: 0.039
    i: 0.039
    r: 0.039
    u: 0.038
    y: 0.039
    z: 0.039
  highSNR: false
  input: None
  km: &id007
    g: 0.213
    i: 0.096
    r: 0.126
    u: 0.491
    y: 0.17
    z: 0.069
  m5: &id008 {}
  majorCol: major
  minorCol: minor
  msky: &id009
    g: 22.26
    i: 20.48
    r: 21.2
    u: 22.99
    y: 18.61
    z: 19.6
  nVisYr: &id010
    g: 8.0
    i: 18.4
    r: 18.4
    u: 5.6
    y: 16.0
    z: 16.0
  nYrObs: 10.0
  name: lsst_error
  ndFlag: .nan
  ndMode: flag
  output_mode: default
  renameDict: &id011
    g: mag_g_lsst
    i: mag_i_lsst
    r: mag_r_lsst
    u: mag_u_lsst
    y: mag_y_lsst
    z: mag_z_lsst
  scale: &id012 {}
  seed: 39
  sigLim: 0
  sigmaSys: 0.005
  theta: &id013
    g: 0.77
    i: 0.71
    r: 0.73
    u: 0.81
    y: 0.68
    z: 0.69
  tvis: 30.0
  validate: true
lsst_error_0:
  Cm: *id005
  aMax: 2.0
  aMin: 0.7
  absFlux: false
  airmass: 1.2
  aliases:
    input: output_inv_redshift
    output: output_lsst_error_0
  config: null
  decorrelate: true
  errLoc: after
  extendedType: point
  gamma: *id006
  highSNR: false
  input: None
  km: *id007
  m5: *id008
  majorCol: major
  minorCol: minor
  msky: *id009
  nVisYr: *id010
  nYrObs: 10.0
  name: lsst_error_0
  ndFlag: .nan
  ndMode: flag
  output_mode: default
  renameDict: *id011
  scale: *id012
  seed: 17
  sigLim: 0
  sigmaSys: 0.005
  theta: *id013
  tvis: 30.0
  validate: true
quantity_cut_1:
  aliases:
    input: output_lsst_error_0
    output: output_quantity_cut_1
  config: null
  cuts: &id014
    mag_i_lsst: 25.3
    redshift:
    - 0.0
    - 3.0
  input: None
  name: quantity_cut_1
  output_mode: default
  seed: 12345
quantity_cut_2:
  aliases:
    input: output_lsst_error
    output: output_quantity_cut_2
  config: null
  cuts: *id014
  input: None
  name: quantity_cut_2
  output_mode: default
  seed: 12345
test_set:
  aliases:
    output: output_test_set
  config: null
  model: /Users/alicec03/Desktop/Summer_Research/Photo-z-Stress-Test/Photo-z-Stress-Test/data/1e6_trained_flow.pkl
  n_samples: 100000
  name: test_set
  output_mode: default
  seed: 39
